version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  rag_api:
    build: ./rag_api
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=ollama
      - LLM_BASE_URL=http://ollama:11434
      - VECTOR_DB_TYPE=faiss
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  ollama:
  grafana-storage:
  n8n_data: